backend/models/opportunity.js
#15 added volunteer opportunity schema
Wasn't sure about the schema type of time, so I just made it a number, and wasn't sure what to call skills/interests so I just called it skills for now
=> #15 added volunteer opportunity schema

backend/models/volunteer.js, backend/package-lock.json, backend/package.json
Added volunteer schema. Also downloaded Mongoose into package.json. 
I wasn't sure what type to put for some parameters like volunteer experience or work history, so I just defaulted to string/array of strings for now, and we can always change it in the future.
=> #13 Added volunteer schema

backend/models/admin.js
Added the admin schema into the backend directory in models.
=> #14 Added the admin user shcema

backend/.env, backend/index.js, backend/models/opportunity.js, backend/package-lock.json, backend/package.json
#20 added connection to userDB and get all opportunities
This was my first time working with environment variables so I wasn't sure if the userDB url was a part of the commit in the .env file or if we write it in our respective machines, so I didn't include it just to be safe : )
=> #20 added connection to userDB and get all opportunities

backend/index.js, backend/models/opportunity.js, backend/models/volunteer.js
#35 added function to update both Volunteers and Opportunities, and changed schemas to reference each other
Turns out that using the ObjectId and referencing them worked out! Also couldn't think of a super good name for the update method so that's up for change, and I didn't know what field to make the queries for, so I just used email for Volunteer and title for Opportunity.
=> #35 added function to update both Volunteers and Opportunities, and changed schemas

backend/index.js
=> #19 get volunteer using name

backend/index.js, backend/models/opportunity.js, backend/models/volunteer.js, backend/package-lock.json, backend/package.json
#51 updated schemas and added new endpoints
wasn't able to fully test it because I don't think I have access to the opportunity database yet, but I'll be happy to test it once we do
=> #51 updated schemas and added new endpoints

backend/index.js, backend/models/opportunity.js, backend/models/volunteer.js
#64 updated date attribute for schemas
The Date object stores the day along with the time, so just changing the start and end attributes to arrays should be good enough to meet the new requirements
=> #64 updated date attribute for schemas

backend/index.js
#18 get requests for all volunteers for an opportunity
I think that connecting to multiple databases gets kinda complicated, say for our userDB and opportunityDB. A future issue could be to set it up, or if you want I can try figuring it out later
Also kinda weird I think this commit is also included with my later pull request
=> #18 get requests for all volunteers for an opportunity

backend/index.js
=> #74 get opportunity by id

backend/.env, backend/connections.js, backend/index.js, backend/models/opportunity.js, backend/models/volunteer.js
#72 multiple connections and schemas tested
I had trouble adding more than two users to the userDB. Whenever I try to add another one, an error pops up saying that the username field is already null, which is weird cause we're not using a username. I can get all the documents from both databases so if we figure out what's wrong then the volunteer schema will probably work like the opportunity schemas
=> #72 multiple connections and schemas tested

backend/models/opportunity.js, backend/models/volunteer.js
updated schemas to account for clarity in multiple tasks
=> updated schemas to account for clarity in multiple tasks

backend/routes/volunteer.js
- added volunteer related functions from server.js into routes/volunteer.js
=> refactor: Volunteer routes

backend/auth.js, backend/routes/auth.js
Refactoring auth routes from server.js to routes/auth. I did not delete anything from server.js in fear that that would cause problems for other people refactoring. If that is included in refactoring I will fix that.
=> refactor: auth routes

backend/package-lock.json, backend/routes/util.js, frontend/package-lock.json, package-lock.json
I could only find donations as one of the routes that I wouldn't categorize under the other routes. Please let me know if there are other routes that need to be put into this file and I'll fix it. Thanks!
=> refactor other routes

frontend/src/Components/Header/Header.css, frontend/src/Components/Header/Header.js, frontend/src/Components/Header/Navbar.js, frontend/src/Components/SearchOpportunities/SearchOpportunities.js, frontend/src/Pages/AuthenticatedUserDashboard/AuthenticatedUserDashboard.js, frontend/src/Pages/OpportunityDetail/OpportunityDetail.js
Because the database info for "additional information, requirements, items, etc" when blank is: "". I decided to output none on the bullet point instead. Additionally, I fixed some margin issues that would extend the page past it's normal width. 
As for the navbar, I realized we might need to rework the navbar dropdown. Currently, at a certain resolution the dropdown navbar appears to the side of the screen, extending the page width instead of simply appearing to the screen when the button is clicked.
=> 144 fix UI bugs

backend/routes/volunteer.js, backend/server.js
- fixed issue with server crashing 
- fixed router imports in server.js
- fixed imports in volunteer.js
=> fix volunteer and opportunity router in server

backend/routes/opportunity.js, frontend/src/Pages/AddOpportunityForm/AddOpportunityForm.js, frontend/src/Pages/AuthenticatedUserDashboard/AuthenticatedUserDashboard.js, frontend/src/Pages/BMLogHoursPage/BMLogHoursPage.js, frontend/src/Pages/OpportunityDetail/OpportunityDetail.js
I refactored the route names and adjusted the frontend code accordingly.
=> refactor: opportunity route names front/backend

backend/routes/volunteer.js
- added a delete route to Volunteer that deletes a task object in task table of Opportunity
- given an Opportunity Object Id (oppId) and taskId in the request body, removes the task that matches taskId from task table in opportunity object
=> added delete volunteer task route

backend/routes/volunteer.js, backend/server.js, frontend/src/Pages/OpportunityDetail/OpportunityDetail.css, frontend/src/Pages/OpportunityDetail/OpportunityDetail.js, package-lock.json, package.json
A new row was added for the volunteer; however, it makes the table disappear. Which is my next task so I will figure that out I just wanted to use this as a check in. Also, there were a couple linting issues I haven't figured out yet so I temporarily disabled them.
=> feat: button to add volunteer hours
